import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the type for RootLayoutProps
type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }:RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
